version: '3.7'

services:
  httpd:
    image: httpd:2.4
    init: true
    volumes:
      - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./root:/usr/local/apache2/htdocs
      - ./_:/_
    ports:
      - 3084:80
    restart: unless-stopped
