
services:
  httpd:
    image: httpd:2.4
    init: true
    volumes:
      - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./root:/usr/local/apache2/htdocs
      - ./_:/usr/local/apache2/htdocs/_
    networks:
      - default
      - sub
    expose:
      - 80
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=data.coypu.org,metadata.coypu.org
      - LETSENCRYPT_HOST=data.coypu.org,metadata.coypu.org

networks:
  default:
  sub:
    name: reverseproxy_sub
    external: true
